import Head from "next/head";
import Image from "next/image";
import Blog from "../components/Blog";
import styles from "../styles/Home.module.css";

export default function Home({ results }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next + Notion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Notion + <a href="https://nextjs.org">Next</a>
        </h1>

        <div className={styles.grid}>
          <p>TODO: to implement the cards!!!! Click on Title to Navigate! </p>
          {results.map((res) => (
            <div key={res.id}>
              <Blog res={res} />
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const { Client } = require("@notionhq/client");

  const notion = new Client({ auth: process.env.NOTION_API_KEY });
  const { results } = await notion.databases.query({
    database_id: process.env.NOTION_DB_ID,
  });
  return {
    props: {
      results,
    },
  };
}
